version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: expense-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expense_tracker
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: expense-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: expense-api
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/expense_tracker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_REDIS_HOST: redis

volumes:
  mysql_data:

